---
#
# App Manifest configurations
#
playground:
  manifest:
    # This can / will need to be changed in the UI when you're walking through the flow.
    # App names must be unique within a Users account.
    name: "%APP_NAME%"
    # This URL and hook_attributes.url should be configured automatically to work with this codespace.
    # If you see a value like 'CODESPACES_NAME' here, try running .devcontainer/on-create-command.sh
    callback_url: https://%CODESPACES_NAME%-8075.githubpreview.dev/callback 
    hook_attributes:
      url: https://%CODESPACES_NAME%-8077.githubpreview.dev/hooks
    # 👋 Edit this spot here! Update `permissions` to include the permissions you need for your app.
    permissions:
      metadata: read
      issues: write
    # Subscribe to events for your app here
    events:
      - issues
